In [1]:
import tensorflow as tf

In [2]:
one = tf.constant(1)
print(one)
a = tf.constant([3])
b = tf.constant([5])
print(a)
print(b)
c = tf.add(a,b)
print(c)

with tf.Session() as session:
    result = session.run(c)
    print(result)

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Const_1:0", shape=(1,), dtype=int32)
Tensor("Const_2:0", shape=(1,), dtype=int32)
Tensor("Add:0", shape=(1,), dtype=int32)
[8]


In [3]:
# scalars, vectors, matrix, tensors
scalar = tf.constant([2])
vector = tf.constant([2,5,8])
matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]], [[3,4,5],[4,5,6],[5,6,7]], [[1,3,5],[3,5,7],[5,7,9]] ])

with tf.Session() as session:
    result = session.run(scalar)
    print("Scalar:\n", result)
    result = session.run(vector)
    print("Vector:\n", result)
    result = session.run(matrix)
    print("Matrix:\n", result)
    result = session.run(tensor)
    print("Tensor:\n", result)

Scalar:
 [2]
Vector:
 [2 5 8]
Matrix:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]
Tensor:
 [[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[3 4 5]
  [4 5 6]
  [5 6 7]]

 [[1 3 5]
  [3 5 7]
  [5 7 9]]]


In [4]:
m1 = tf.constant([[1,2,3],[2,3,4],[4,5,6]])
m2 = tf.constant([[5,6,7],[8,9,1],[2,0,3]])
op1 = tf.add(m1,m2)
op2 = m1 + m2
op3 = tf.matmul(m1,m2)
with tf.Session() as session:
    result = session.run(op1)
    print("Result with tf operation:\n", result)
    result = session.run(op2)
    print("Result with normal operation:\n", result)
    result = session.run(op3)
    print("Result of matmul operation:\n", result)

Result with tf operation:
 [[ 6  8 10]
 [10 12  5]
 [ 6  5  9]]
Result with normal operation:
 [[ 6  8 10]
 [10 12  5]
 [ 6  5  9]]
Result of matmul operation:
 [[27 24 18]
 [42 39 29]
 [72 69 51]]


In [5]:
# Variables, are updated during optimization. Need initialization
state = tf.Variable(0)
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

init_op = tf.global_variables_initializer()

with tf.Session() as session:
    result = session.run(init_op)
    print(session.run(state))
    for i in range(3):
        session.run(update)
        print(session.run(state))

Instructions for updating:
Colocations handled automatically by placer.
0
1
2
3


In [6]:
# Placeholders
# needed to feed data to your model from outside, need datatype
# data is passed to the model with the feed_dict argument (each placeholder named followed by its respective data)
a = tf.placeholder(tf.float32)
b = a * 2
with tf.Session() as session:
    result = session.run(b, feed_dict={a:3.5})
    print(result)
    
    new_dict = {a: [[[1,2,3],[4,5,6]], [[1.5,2.5,3.5],[4.5,5.5,6.5]]]}
    result = session.run(b, feed_dict=new_dict)
    print(result)

7.0
[[[ 2.  4.  6.]
  [ 8. 10. 12.]]

 [[ 3.  5.  7.]
  [ 9. 11. 13.]]]
